# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: indigo
  font_size: m

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'National Association of Insurance Commissioners, Center for Insurance Policy and Research'
    description: 'Hans Zhu – Postdoctoral Researcher at NAIC - CIPR. Empirical IO, health and insurance economics. PhD in Economics, Northwestern University.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Hans Zhu'

# Site footer
footer:
  copyright:
    notice: '© {year} Hans Zhu. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
